import numpy
Matrix1=numpy.matrix([[1,2,3],[1,1,1],[1,1,1]])
Matrix2=numpy.matrix([[1,0,0],[0,1,0],[0,0,1]])
print("Matrix 1 =\n",Matrix1)
print("Matrix 2 =\n",Matrix2)
Matrix3=numpy.add(Matrix1,Matrix2)
Matrix4=numpy.subtract(Matrix1,Matrix2)
Matrix5=numpy.matmul(Matrix1,Matrix2)
Matrix6=numpy.transpose(Matrix1)
print("Matrix 1 + Matrix 2 =\n",Matrix3)
print("Matrix 1 - Matrix 2 =\n",Matrix4)
print("Matrix 1 * Matrix 2 =\n",Matrix5)
print("2 * Mtarix 1=\n",2*Matrix1)
print("Transpose of Matrix 1 =\n",Matrix6)
